### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [1j01/scribble#1]
I drew a glyph for each character then clicked draw something with this font but only get a bunch of squiggly lines trailing down to the right

**Comment by 1j01** [comment]
Sorry, yeah I've apparently just left this project in a totally broken state.

I've updated the readme, and removed links to the demo, to avoid wasting anyone else's time.
Maybe I'll slap a "THIS DOESN'T WORK" message over the demo as well.

**Comment by 1j01** [comment]
![added THIS DOESN'T WORK message](https://user-images.githubusercontent.com/3630663/66271348-f77dd480-e82a-11e9-86b6-a42b8ef7b05e.png)
